"""
Django settings for PomoTask project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kd&mc!c0e+gvdpy9hs#rlqfq08l2c*gc5n0xl86f%&ar*veyu1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

CRONJOBS = [
    ('* * * * *', 'python manage.py remainder_notification_sender')
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "Task.apps.TaskConfig",
    'corsheaders',
    'Goal',
    'django_crontab'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'PomoTask.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PomoTask.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'pomotask',  # Name of your MongoDB database
        'ENFORCE_SCHEMA': False,  # Optional: Set to False if you're not enforcing Django's schema
        'CLIENT': {
            'host': 'mongodb://localhost:27017',  # MongoDB connection URL
            # Optional client options
            'username': config('DB_USER'),  # Only if authentication is enabled
            'password': config('DB_PASSWORD'),  # Only if authentication is enabled
            'authSource': 'admin',  # Specify the database for authentication
            'authMechanism': 'SCRAM-SHA-1',  # Optional: Depends on the mechanism used by your MongoDB setup
        },
        'CONN_MAX_AGE': 600
    }
}

""" DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'pomotask',  # Name of your MongoDB database
        'ENFORCE_SCHEMA': False,  # Optional: Set to False if you're not enforcing Django's schema
        'CLIENT': {
            'host': 'mongodb://my-shard-00-02.rbc8g.mongodb.net:27017',  # MongoDB connection URL
            # Optional client options
            'username': 'praveen',  # Only if authentication is enabled
            'password': 'hackme',  # Only if authentication is enabled
            'authSource': 'admin',        # Specify the database for authentication
            'authMechanism': 'SCRAM-SHA-1',  # Optional: Depends on the mechanism used by your MongoDB setup
            'ssl': True,
        },
        'CONN_MAX_AGE': 600
    }
} """

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CORS_ALLOW_ALL_ORIGINS = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
