# Generated by Django 4.1.13 on 2026-09-23 10:15

import Dairy.models.dairy
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.CharField(default=Dairy.models.dairy.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
