# Generated by Django 4.1.13 on 2026-06-09 11:07

import Task.models.tags
import Task.models.task
import Task.models.task_timing
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.CharField(default=Task.models.tags.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('home_page_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=Task.models.task.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('important_flag', models.BooleanField(default=False, null=True)),
                ('my_day_date', models.DateField(null=True)),
                ('reminder_date_time', models.DateTimeField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('from_time', models.TimeField(null=True)),
                ('to_time', models.TimeField(null=True)),
                ('estimate', models.BigIntegerField(null=True)),
                ('total_seconds', models.BigIntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[('0', 'ToDo'), ('1', 'Done'), ('2', 'In Progress'), ('3', 'Deleted')], default='0')),
                ('tags', models.Field(verbose_name=models.ManyToManyField(related_name='tasks', to='Task.tags'))),
                ('goal', models.Field(verbose_name=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='Goal.goal'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTiming',
            fields=[
                ('id', models.CharField(default=Task.models.task_timing.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Task.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Task.task')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='child_tasks', to='Task.task')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parent_tasks', to='Task.task')),
            ],
        ),
    ]
