# Generated by Django 4.1.13 on 2026-06-09 11:07

import Goal.models.goal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(default=Goal.models.goal.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[('0', 'Year'), ('1', 'Month'), ('2', 'Week')])),
                ('status', models.IntegerField(choices=[('0', 'ToDo'), ('1', 'Done'), ('2', 'In Progress')], default='0')),
                ('months', models.JSONField(blank=True, default=list)),
                ('linked_goals', models.JSONField(blank=True, default=list)),
                ('year', models.IntegerField(blank=True)),
                ('month', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
